//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diabidabackend.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diabidadbEntities : DbContext
    {
        public diabidadbEntities()
            : base("name=diabidadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<appointment> appointments { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<bpmInterval> bpmIntervals { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<clinic> clinics { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<clinicByPatient> clinicByPatients { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<comment> comments { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<commentResponse> commentResponses { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<heartbeatHistory> heartbeatHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<heightHistory> heightHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<notification> notifications { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<specialistByPatient> specialistByPatients { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<user> users { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<userType> userTypes { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<weightHistory> weightHistories { get; set; }
    }
}
